# 开发环境

#端口号，内置对象
server:
  port: 8088

const:
  # 服务器地址
  cloud:
    host: localhost
    port: ${server.port}
    baseUrl: http://${const.cloud.host}:${const.cloud.port}
  # 数据库地址
  sql:
    host: ${const.cloud.host}
    port: 3306
    baseUrl:  http://${const.sql.host}:${const.sql.port}

  # 本机静态资源地址
  static_dir: /norman/oss/

spring:
  #数据库连接信息
  datasource:
    url: "jdbc:mysql://${const.sql.host}:${const.sql.port}/norman?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true"
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  # redis缓存数据库
  redis:
    host: 111.229.116.
    port: 6379
    password:



